name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # Setup Node.js and cache npm dependencies
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Set base and head SHAs for affected commands
      - name: Set Nx SHAs
        uses: nrwl/nx-set-shas@v4

      # Run affected lint, test, and build tasks
      - name: Run affected lint, test, and build
        run: npx nx affected -t lint test build --parallel
